[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = ["rm -rf node_modules/.cache", "npm ci"]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]

[start]
cmd = "node dist/main.js"
