[build]
builder = "NIXPACKS"
buildCommand = "chmod +x build.sh && ./build.sh"

[deploy]
startCommand = "node dist/main.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
buildCommand = "chmod +x build.sh && ./build.sh"
