name: Build iOS IPA

on:
  workflow_dispatch: # Manual trigger only
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'CLOUD_BUILD_INSTRUCTIONS.md'

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Setup iOS Simulator
      run: |
        xcrun simctl list devices
        
    - name: Install dependencies
      run: |
        npm ci
        npx expo install --fix
        
    - name: Clean and generate iOS project
      run: |
        # Remove existing ios directory if it exists
        if [ -d "ios" ]; then
          echo "Removing existing ios directory"
          rm -rf ios
        fi
        
        # Generate iOS project
        echo "Generating iOS project..."
        npx expo prebuild --platform ios
        
        # Verify the project was created
        if [ -d "ios" ]; then
          echo "✅ iOS project generated successfully"
          ls -la ios/
        else
          echo "❌ iOS project generation failed"
          exit 1
        fi
        
    - name: Install iOS dependencies
      run: |
        cd ios
        pod install --repo-update
        
    - name: Verify iOS project structure
      run: |
        cd ios
        echo "=== iOS Project Structure ==="
        ls -la
        echo "=== Looking for workspace files ==="
        find . -name "*.xcworkspace" -o -name "*.xcodeproj"
        
    - name: Build iOS App for Simulator (No Code Signing Required)
      run: |
        cd ios
        # Try workspace first, fallback to project
        if [ -f "TijaniyahPro.xcworkspace" ]; then
          echo "Building with workspace for iOS Simulator..."
          xcodebuild -workspace TijaniyahPro.xcworkspace \
                     -scheme TijaniyahPro \
                     -configuration Debug \
                     -destination 'platform=iOS Simulator,name=iPhone 16,OS=26.0' \
                     -derivedDataPath ./build \
                     build
        elif [ -d "TijaniyahPro.xcodeproj" ]; then
          echo "Building with project for iOS Simulator..."
          xcodebuild -project TijaniyahPro.xcodeproj \
                     -scheme TijaniyahPro \
                     -configuration Debug \
                     -destination 'platform=iOS Simulator,name=iPhone 16,OS=26.0' \
                     -derivedDataPath ./build \
                     build
        else
          echo "❌ No workspace or project found!"
          echo "Available files:"
          ls -la
          exit 1
        fi
                   
    - name: Check for iOS build artifacts
      run: |
        echo "Checking for iOS build artifacts..."
        if [ -d "ios/build" ]; then
          echo "✅ iOS build completed successfully"
          ls -la ios/build/
          find ios/build/ -name "*.app" -type d
        else
          echo "❌ iOS build failed"
          exit 1
        fi
        
    - name: Upload iOS build
      uses: actions/upload-artifact@v4
      with:
        name: tijaniyah-pro-ios-build
        path: ios/build/
        retention-days: 30
        
    - name: Upload build logs (on failure)
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: ios-build-logs
        path: ios/
        retention-days: 7
