name: Build Tijaniyah Pro APK

on:
  workflow_dispatch: # Manual trigger
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'CLOUD_BUILD_INSTRUCTIONS.md'

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        
    - name: Install dependencies
      run: |
        npm ci
        npx expo install --fix
        
    - name: Check if android directory exists
      run: |
        if [ -d "android" ]; then
          echo "Android directory exists, removing it for clean build"
          rm -rf android
        fi
        
    - name: Generate Android project
      run: |
        npx expo prebuild --platform android
        echo "Android project generated successfully"
        ls -la android/
        
    - name: Verify Android project structure
      run: |
        echo "Checking Android project structure:"
        ls -la android/
        ls -la android/app/
        echo "Gradle wrapper exists:"
        ls -la android/gradlew
        
    - name: Build Release APK
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleRelease --no-daemon --stacktrace
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: tijaniyah-pro-apk
        path: android/app/build/outputs/apk/release/*.apk
        retention-days: 30
        
    - name: Upload build logs (on failure)
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-logs
        path: android/
        retention-days: 7
