name: Build APK (Debug Version)

on:
  workflow_dispatch: # Manual trigger only

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Show environment info
      run: |
        echo "Node version:"
        node --version
        echo "NPM version:"
        npm --version
        echo "Java version:"
        java --version
        echo "Android SDK:"
        echo $ANDROID_HOME
        
    - name: Install dependencies
      run: |
        npm ci
        echo "Dependencies installed successfully"
        
    - name: Fix Expo dependencies
      run: |
        npx expo install --fix
        echo "Expo dependencies fixed"
        
    - name: Clean any existing android directory
      run: |
        if [ -d "android" ]; then
          echo "Removing existing android directory"
          rm -rf android
        fi
        echo "Clean slate ready"
        
    - name: Generate Android project
      run: |
        echo "Starting Android project generation..."
        npx expo prebuild --platform android --clear
        echo "Android project generation completed"
        
    - name: Verify project structure
      run: |
        echo "=== Project Structure ==="
        ls -la
        echo "=== Android Directory ==="
        ls -la android/
        echo "=== Android App Directory ==="
        ls -la android/app/
        echo "=== Gradle Files ==="
        ls -la android/*.gradle
        echo "=== Gradle Wrapper ==="
        ls -la android/gradlew
        
    - name: Make gradlew executable
      run: |
        cd android
        chmod +x gradlew
        echo "Gradle wrapper is now executable"
        
    - name: Test Gradle setup
      run: |
        cd android
        ./gradlew --version
        echo "Gradle version check completed"
        
    - name: Build Release APK
      run: |
        cd android
        echo "Starting APK build..."
        ./gradlew assembleRelease --no-daemon --stacktrace --info
        echo "APK build completed"
        
    - name: Verify APK was created
      run: |
        echo "=== Checking for APK files ==="
        find android/app/build/outputs/apk/ -name "*.apk" -type f
        echo "=== APK directory contents ==="
        ls -la android/app/build/outputs/apk/release/
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: tijaniyah-pro-apk-debug
        path: android/app/build/outputs/apk/release/*.apk
        retention-days: 30
        
    - name: Upload build logs
      uses: actions/upload-artifact@v4
      with:
        name: build-logs-debug
        path: |
          android/
          *.log
        retention-days: 7
